# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app import flight_service_pb2 as flight__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FlightServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchFlights = channel.unary_unary(
                '/flight.FlightService/SearchFlights',
                request_serializer=flight__service__pb2.SearchFlightsRequest.SerializeToString,
                response_deserializer=flight__service__pb2.SearchFlightsResponse.FromString,
                )
        self.GetFlight = channel.unary_unary(
                '/flight.FlightService/GetFlight',
                request_serializer=flight__service__pb2.GetFlightRequest.SerializeToString,
                response_deserializer=flight__service__pb2.Flight.FromString,
                )
        self.ReserveSeats = channel.unary_unary(
                '/flight.FlightService/ReserveSeats',
                request_serializer=flight__service__pb2.ReserveSeatsRequest.SerializeToString,
                response_deserializer=flight__service__pb2.ReserveSeatsResponse.FromString,
                )
        self.ReleaseReservation = channel.unary_unary(
                '/flight.FlightService/ReleaseReservation',
                request_serializer=flight__service__pb2.ReleaseReservationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class FlightServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveSeats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFlights,
                    request_deserializer=flight__service__pb2.SearchFlightsRequest.FromString,
                    response_serializer=flight__service__pb2.SearchFlightsResponse.SerializeToString,
            ),
            'GetFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlight,
                    request_deserializer=flight__service__pb2.GetFlightRequest.FromString,
                    response_serializer=flight__service__pb2.Flight.SerializeToString,
            ),
            'ReserveSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveSeats,
                    request_deserializer=flight__service__pb2.ReserveSeatsRequest.FromString,
                    response_serializer=flight__service__pb2.ReserveSeatsResponse.SerializeToString,
            ),
            'ReleaseReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseReservation,
                    request_deserializer=flight__service__pb2.ReleaseReservationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flight.FlightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlightService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.FlightService/SearchFlights',
            flight__service__pb2.SearchFlightsRequest.SerializeToString,
            flight__service__pb2.SearchFlightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.FlightService/GetFlight',
            flight__service__pb2.GetFlightRequest.SerializeToString,
            flight__service__pb2.Flight.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReserveSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.FlightService/ReserveSeats',
            flight__service__pb2.ReserveSeatsRequest.SerializeToString,
            flight__service__pb2.ReserveSeatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flight.FlightService/ReleaseReservation',
            flight__service__pb2.ReleaseReservationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
